const CONTRACT_ERRORS: Record<string, string> = {
  u202: "Job not found.",
  u203: "This action is not valid for the current job state.",
  u204: "The job has expired.",
  u205: "Enter a valid budget.",
  u207: "Only the client can perform this action.",
  u208: "Only the assigned provider can submit work.",
  u209: "Only the evaluator can settle or reject this job.",
  u210: "This job is already funded.",
  u212: "Enter a job description.",
  u213: "Client, provider and evaluator must be different wallets.",
  u214: "This wallet has already rated this job.",
  u215: "Rating must be between 1 and 5.",
  u216: "This job has not expired yet.",
  u302: "Job not found.",
  u303: "This action is not valid for the current job state.",
  u304: "The job has expired.",
  u305: "Enter a valid budget.",
  u307: "Only the client can perform this action.",
  u308: "Only the assigned provider can submit work.",
  u309: "Only the independent evaluator can perform this action.",
  u310: "This job is already funded.",
  u311: "The configured payment token is not canonical sBTC.",
  u312: "Enter a job description.",
  u313: "Client, provider and evaluator must be different wallets.",
  u314: "This wallet has already rated this job.",
  u315: "Rating must be between 1 and 5.",
  u316: "This job has not expired yet.",
  u602: "Job not found.",
  u603: "This action is not valid for the current job state.",
  u604: "The job expired before work was submitted.",
  u605: "Enter a valid budget.",
  u607: "Only the client can perform this action.",
  u608: "Only the assigned provider can submit work.",
  u609: "Only the independent evaluator can perform this action.",
  u610: "This job is already funded.",
  u612: "Enter a job description.",
  u613: "Client, provider and evaluator must be different wallets.",
  u614: "This wallet has already rated this job.",
  u615: "Rating must be between 1 and 5.",
  u616: "This job has not expired yet.",
  u617: "The evaluator review window has closed.",
  u618: "The Bitcoin review deadline has not passed yet.",
  u619: "This job does not have a review deadline.",
  u623: "There is no pending reputation update for this job.",
  u702: "Job not found.",
  u703: "This action is not valid for the current job state.",
  u704: "The job expired before work was submitted.",
  u705: "Enter a valid budget.",
  u707: "Only the client can perform this action.",
  u708: "Only the assigned provider can submit work.",
  u709: "Only the independent evaluator can perform this action.",
  u710: "This job is already funded.",
  u711: "The supplied token does not match the sBTC token pinned to this job.",
  u712: "Enter a job description.",
  u713: "Client, provider and evaluator must be different wallets.",
  u714: "This wallet has already rated this job.",
  u715: "Rating must be between 1 and 5.",
  u716: "This job has not expired yet.",
  u717: "The evaluator review window has closed.",
  u718: "The Bitcoin review deadline has not passed yet.",
  u719: "This job does not have a review deadline.",
  u723: "There is no pending reputation update for this job.",
  u724: "This job does not have a pinned sBTC token.",
  u802: "Job not found.",
  u803: "This action is not valid for the current autonomous job state.",
  u809: "Only Nayori can record this decision.",
  u817: "Nayori's evaluation window has closed.",
  u824: "The autonomous evaluation protocol is not configured.",
  u828: "The recorded decision is invalid.",
  u829: "No Nayori decision exists for this job.",
  u830: "Only the client may appeal an approval; only the provider may appeal a rejection.",
  u831: "The appeal window has closed.",
  u832: "The decision cannot be finalized before the appeal deadline.",
  u833: "Only the job's human appeal authority may resolve this dispute.",
  u834: "Provide a valid non-zero evidence commitment.",
  u835: "The human resolution window has closed.",
  u836: "The appeal timeout has not passed yet.",
  u902: "Job not found.",
  u903: "This action is not valid for the current autonomous job state.",
  u909: "Only Nayori can record this decision.",
  u911: "The supplied token does not match the sBTC token pinned to this job.",
  u917: "Nayori's evaluation window has closed.",
  u925: "The autonomous evaluation protocol is not configured.",
  u929: "The recorded decision is invalid.",
  u930: "No Nayori decision exists for this job.",
  u931: "Only the client may appeal an approval; only the provider may appeal a rejection.",
  u932: "The appeal window has closed.",
  u933: "The decision cannot be finalized before the appeal deadline.",
  u934: "Only the job's human appeal authority may resolve this dispute.",
  u935: "Provide a valid non-zero evidence commitment.",
  u936: "The human resolution window has closed.",
  u937: "The appeal timeout has not passed yet.",
};

export function humanizeContractError(error: unknown): string {
  const raw =
    error instanceof Error ? error.message : typeof error === "string" ? error : String(error);
  const code = raw.match(/\bu\d{3}\b/)?.[0];
  if (code && CONTRACT_ERRORS[code]) return CONTRACT_ERRORS[code];
  if (/cancel|reject/i.test(raw)) return "The wallet request was cancelled.";
  if (/address|principal/i.test(raw)) return "Enter a valid Stacks address for this network.";
  return "The transaction could not be submitted. Check the job state and wallet network.";
}
